plugins {
    id 'com.android.application'
}

def ciVersionCode = (System.getenv('GITHUB_RUN_NUMBER') ?: '1') as Integer

android {
    namespace 'com.qxdnzbl.shuangjichuan'
    compileSdk 35

    defaultConfig {
        applicationId 'com.qxdnzbl.shuangjichuan'
        minSdk 26
        targetSdk 34
        versionCode ciVersionCode
        versionName "1.0." + ciVersionCode
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    androidTestImplementation 'androidx.test:core:1.6.1'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}