plugins { id 'com.android.application' }

android {
    namespace 'com.qxdnzbl.shuangjichuan'
    compileSdk 35
    defaultConfig {
        applicationId 'com.qxdnzbl.shuangjichuan.live'
        minSdk 26
        targetSdk 34
        versionCode 200
        versionName '2.0'
    }
    buildTypes {
        debug { debuggable true }
        release { minifyEnabled false }
    }
}
