plugins {
    id 'com.android.application'
}

android {
    namespace 'com.qxdnzbl.hotspotshare'
    compileSdk 35

    defaultConfig {
        applicationId 'com.qxdnzbl.hotspotshare'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.1.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.zxing:core:3.5.3'

    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
}
