(function(){
'use strict';
var DB_NAME='immersiveMusicIOS', STORE='tracks';
var db=null, tracks=[], queue=[], currentId=null, currentUrl=null, loopOne=false, lastPage='home';
var audio=new Audio(); audio.preload='metadata';
function $(id){return document.getElementById(id)}
function openDb(){return new Promise(function(resolve,reject){var r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=function(){var d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=function(){db=r.result;resolve(db)};r.onerror=function(){reject(r.error||new Error('数据库打开失败'))}})}
var ready=openDb().then(function(){return readAll()}).then(function(list){tracks=list.sort(function(a,b){return a.createdAt-b.createdAt});restoreState();renderAll();if(currentId&&byId(currentId))loadTrack(currentId,false);else if(queue[0])loadTrack(queue[0],false);else resetPlayer();return true}).catch(function(e){console.error('INIT',e);renderAll();return false});
function readAll(){return new Promise(function(resolve,reject){var r=db.transaction(STORE,'readonly').objectStore(STORE).getAll();r.onsuccess=function(){resolve(r.result||[])};r.onerror=function(){reject(r.error)}})}
function put(t){return new Promise(function(resolve,reject){var r=db.transaction(STORE,'readwrite').objectStore(STORE).put(t);r.onsuccess=function(){resolve()};r.onerror=function(){reject(r.error)}})}
function remove(id){return new Promise(function(resolve,reject){var r=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);r.onsuccess=function(){resolve()};r.onerror=function(){reject(r.error)}})}
function makeId(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9)}
function byId(id){for(var i=0;i<tracks.length;i++)if(tracks[i].id===id)return tracks[i];return null}
function safeText(s){return String(s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function baseName(name){return String(name||'').replace(/\.[^.]+$/,'')||'未命名歌曲'}
function readBuffer(blob){return new Promise(function(resolve,reject){var fr=new FileReader();fr.onload=function(){resolve(fr.result)};fr.onerror=function(){reject(fr.error||new Error('文件读取失败'))};fr.readAsArrayBuffer(blob)})}
function decode(bytes,enc){try{return new TextDecoder(enc||'utf-8').decode(bytes).replace(/\u0000/g,'').trim()}catch(e){return''}}
function id3(buf,fallback){try{var b=new Uint8Array(buf);if(b.length<10||String.fromCharCode(b[0],b[1],b[2])!=='ID3')return fallback;var ver=b[3],size=((b[6]&127)<<21)|((b[7]&127)<<14)|((b[8]&127)<<7)|(b[9]&127),p=10,end=Math.min(b.length,10+size),title='',artist='';while(p+10<=end){var k=String.fromCharCode(b[p],b[p+1],b[p+2],b[p+3]);var n=ver===4?((b[p+4]&127)<<21)|((b[p+5]&127)<<14)|((b[p+6]&127)<<7)|(b[p+7]&127):((b[p+4]<<24)|(b[p+5]<<16)|(b[p+6]<<8)|b[p+7])>>>0;if(!n||p+10+n>end)break;if(k==='TIT2'||k==='TPE1'){var body=b.slice(p+10,p+10+n),e=body[0],txt='';if(e===0)txt=decode(body.slice(1),'iso-8859-1');else if(e===3)txt=decode(body.slice(1),'utf-8');else txt=decode(body.slice(1),'utf-16');if(k==='TIT2')title=txt;if(k==='TPE1')artist=txt}p+=10+n}return{title:title||fallback.title,artist:artist||fallback.artist}}catch(e){return fallback}}
async function importFiles(files){await ready;for(var i=0;i<files.length;i++){var f=files[i],fallback={title:baseName(f.name),artist:'本地音乐'},meta=fallback;var data=await readBuffer(f);try{var head=data.byteLength>512*1024?data.slice(0,512*1024):data;meta=id3(head,fallback)}catch(e){console.warn('METADATA',e)}var t={id:makeId(),name:f.name,title:meta.title,artist:meta.artist,type:f.type||'audio/*',size:f.size,data:data,createdAt:Date.now()};await put(t);tracks.push(t);queue.push(t.id)}saveState();renderAll();if(!currentId&&queue[0])loadTrack(queue[0],false)}
function saveState(){try{localStorage.setItem('immersive.ios.queue',JSON.stringify(queue));localStorage.setItem('immersive.ios.current',currentId||'');localStorage.setItem('immersive.ios.loop',loopOne?'1':'0')}catch(e){}}
function restoreState(){try{var valid={};tracks.forEach(function(t){valid[t.id]=1});var q=JSON.parse(localStorage.getItem('immersive.ios.queue')||'[]');queue=q.filter(function(x){return valid[x]});tracks.forEach(function(t){if(queue.indexOf(t.id)<0)queue.push(t.id)});currentId=localStorage.getItem('immersive.ios.current')||null;if(currentId&&!valid[currentId])currentId=null;loopOne=localStorage.getItem('immersive.ios.loop')==='1';audio.loop=loopOne}catch(e){queue=tracks.map(function(t){return t.id})}}
function colorFor(s){var a=['#2c263b','#173846','#3b3029','#25372e','#402a33','#29324b','#3b3526'];var h=0;for(var i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return a[h%a.length]}
function sourceBlob(t){if(t&&t.data)return new Blob([t.data],{type:t.type||'audio/*'});if(t&&t.blob)return t.blob;return null}
function loadTrack(id,auto){var t=byId(id);if(!t)return;var source=sourceBlob(t);if(!source)return;if(currentUrl)URL.revokeObjectURL(currentUrl);currentId=id;currentUrl=URL.createObjectURL(source);audio.src=currentUrl;audio.load();document.documentElement.style.setProperty('--bg',colorFor(t.title+t.artist));$('nowTitle').textContent=t.title;$('nowArtist').textContent=t.artist;$('discLabel').textContent=t.title;saveState();renderAll();if(auto){var p=audio.play();if(p&&p.catch)p.catch(function(){})}}
function fmt(s){if(!isFinite(s)||s<0)return'0:00';var m=Math.floor(s/60),x=Math.floor(s%60);return m+':'+(x<10?'0':'')+x}
function resetPlayer(){audio.pause();$('nowTitle').textContent='还没有歌曲';$('nowArtist').textContent='去音乐库添加';$('discLabel').textContent='沉浸音乐';$('seek').value=0;$('cur').textContent='0:00';$('dur').textContent='0:00';setPlaying()}
function setPlaying(){var on=!audio.paused&&!audio.ended;$('disc').classList.toggle('playing',on);$('needle').classList.toggle('on',on);$('play').textContent=on?'Ⅱ':'▶'}
function next(dir){if(!queue.length)return;var i=queue.indexOf(currentId);if(i<0)i=0;else i=(i+dir+queue.length)%queue.length;loadTrack(queue[i],true)}
function row(t,more){return'<div class="row" data-id="'+t.id+'"><div class="row-main"><div class="row-title">'+safeText(t.title)+'</div><div class="row-sub">'+safeText(t.artist)+'</div></div>'+(more?'<button class="more" data-more="'+t.id+'">⋮</button>':'')+'<div class="del-layer"><button class="del" data-del="'+t.id+'">删除</button></div></div>'}
function bind(root,libraryMode,queueMode){Array.prototype.forEach.call(root.querySelectorAll('.row'),function(r){var id=r.getAttribute('data-id'),timer=null;var main=r.querySelector('.row-main');main.onclick=function(){if(r.classList.contains('delete')){r.classList.remove('delete');return}loadTrack(id,true);show('home')};if(queueMode){main.ontouchstart=function(){timer=setTimeout(function(){r.classList.add('delete')},520)};main.ontouchend=function(){clearTimeout(timer)};main.ontouchcancel=function(){clearTimeout(timer)}}});Array.prototype.forEach.call(root.querySelectorAll('[data-more]'),function(b){b.onclick=function(e){e.stopPropagation();var r=b.closest('.row');Array.prototype.forEach.call(root.querySelectorAll('.row'),function(x){if(x!==r)x.classList.remove('delete')});r.classList.toggle('delete')}});Array.prototype.forEach.call(root.querySelectorAll('[data-del]'),function(b){b.onclick=async function(e){e.stopPropagation();var id=b.getAttribute('data-del');if(queueMode){queue=queue.filter(function(x){return x!==id})}else if(libraryMode){await remove(id);tracks=tracks.filter(function(x){return x.id!==id});queue=queue.filter(function(x){return x!==id})}if(currentId===id){currentId=null;if(queue.length)loadTrack(queue[0],false);else resetPlayer()}saveState();renderAll()}})}
function renderLibrary(){var e=$('libraryList');e.innerHTML=tracks.length?tracks.map(function(t){return row(t,true)}).join(''):'<div class="empty">还没有音乐。<br>点右上角“＋”从 iPhone 的“文件”里添加歌曲。</div>';bind(e,true,false)}
function renderQueue(){var arr=queue.map(byId).filter(Boolean),e=$('queueList');e.innerHTML=arr.length?arr.map(function(t){return row(t,false)}).join(''):'<div class="empty">播放列表为空</div>';bind(e,false,true)}
function renderSearch(){var q=$('searchInput').value.trim().toLowerCase(),arr=q?tracks.filter(function(t){return(t.title+' '+t.artist).toLowerCase().indexOf(q)>=0}):[],e=$('searchList');e.innerHTML=arr.map(function(t){return row(t,false)}).join('');bind(e,false,false)}
function renderAll(){renderLibrary();renderQueue();renderSearch();$('loopBtn').style.opacity=loopOne?'1':'.55'}
function show(name){['home','library','search'].forEach(function(x){$(x).classList.toggle('active',x===name)});if(name!=='search')lastPage=name}
Array.prototype.forEach.call(document.querySelectorAll('[data-page]'),function(b){b.onclick=function(){show(b.getAttribute('data-page'))}});
$('openSearch').onclick=function(){show('search');setTimeout(function(){$('searchInput').focus()},60)};$('back').onclick=function(){show(lastPage)};$('searchInput').oninput=renderSearch;$('add').onclick=function(){$('fileInput').click()};$('fileInput').onchange=async function(){var fs=Array.prototype.slice.call(this.files||[]);this.value='';if(!fs.length)return;try{await importFiles(fs)}catch(e){console.error('IMPORT',e);alert('添加失败，请重新选择文件。')}};
$('play').onclick=function(){if(!currentId&&queue[0])loadTrack(queue[0],false);if(!audio.src)return;if(audio.paused)audio.play();else audio.pause()};$('prev').onclick=function(){next(-1)};$('next').onclick=function(){next(1)};$('loopBtn').onclick=function(){loopOne=!loopOne;audio.loop=loopOne;saveState();renderAll()};$('queueBtn').onclick=function(){$('queueSheet').classList.add('show');renderQueue()};$('scrim').onclick=function(){$('queueSheet').classList.remove('show')};$('seek').oninput=function(){if(isFinite(audio.duration)&&audio.duration>0)audio.currentTime=audio.duration*Number(this.value)/1000};
audio.addEventListener('play',setPlaying);audio.addEventListener('pause',setPlaying);audio.addEventListener('ended',function(){if(!loopOne)next(1)});audio.addEventListener('loadedmetadata',function(){$('dur').textContent=fmt(audio.duration)});audio.addEventListener('timeupdate',function(){$('cur').textContent=fmt(audio.currentTime);$('dur').textContent=fmt(audio.duration);if(isFinite(audio.duration)&&audio.duration>0)$('seek').value=Math.round(audio.currentTime/audio.duration*1000)});
$('hideTip').onclick=function(){$('installTip').classList.remove('show');try{localStorage.setItem('immersive.ios.tip','1')}catch(e){}};
function installTip(){var standalone=navigator.standalone===true||(window.matchMedia&&window.matchMedia('(display-mode: standalone)').matches);if(!standalone&&!localStorage.getItem('immersive.ios.tip'))setTimeout(function(){$('installTip').classList.add('show')},900)}
if('mediaSession'in navigator){try{navigator.mediaSession.setActionHandler('play',function(){audio.play()});navigator.mediaSession.setActionHandler('pause',function(){audio.pause()});navigator.mediaSession.setActionHandler('previoustrack',function(){next(-1)});navigator.mediaSession.setActionHandler('nexttrack',function(){next(1)})}catch(e){}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(function(e){console.warn('SW',e)});
installTip();
})();